export const SET_TEMP_AUTH_DATA = 'SET_TEMP_AUTH_DATA';
export const DO_REGISTER = 'DO_REGISTER';
export const SET_TEMP_AUTH_LOADING = 'SET_TEMP_AUTH_LOADING';
export const SET_TEMP_AUTH_ERROR = 'SET_TEMP_AUTH_ERROR';
export const SET_TEMP_IS_VERIFYING = 'SET_TEMP_IS_VERIFYING';
export const SET_TEMP_AUTH_SUCCESS = 'SET_TEMP_AUTH_SUCCESS';
