export const SET_TRANSACTION_DETAIL = 'SET_TRANSACTION_DETAIL';
export const SET_DATA_TO_SEND = 'SET_DATA_TO_SEND';
export const CLEAR_DATA_TO_SEND = 'CLEAR_DATA_TO_SEND';
export const SET_TRANSACTION_LOADING = 'SET_TRANSACTION_LOADING';
export const SET_TRANSACTION_ERROR = 'SET_TRANSACTION_ERROR';
