export const SET_VEHICLES = 'GET_VEHICLES';

export const SET_LOADING = 'SET_LOADING_VEHICLES';
export const SET_LOADING_MORE = 'SET_LOADING_MORE_VEHICLES';

export const SET_ERROR = 'SET_ERROR';

export const SET_VEHICLE = 'SET_VEHICLE';

export const SET_CARS = 'SET_CARS';
export const SET_MOTORCYCLES = 'SET_MOTORCYCLES';
export const SET_BIKES = 'SET_BIKES';

export const SET_QUERY = 'SET_VEHICLE_QUERY';

export const CLEAR_VEHICLES = 'CLEAR_VEHICLES';

export const SET_DATA_TO_FILTER = 'SET_DATA_TO_FILTER_VEHICLE';
